### PR TITLE
Update to support vertical flip

### LINKED ISSUE #1: Add support for vertical card flip.
Add css to allow for vertical card flip.

### PR DESCRIPTION
**Pull request by sbardian**
Closes #1

### CODE REVIEW

**Comment by sbardian** [comment]
Hmm seems we have an issue with tabs vs. spaces.  I tried fixing this by changing your .editorconfig to use spaces, since that appears to be what is in the source code, but as you can see, it doesn't appear to work. . . At least on GH's end.  Looks fine in vscode. . .

**Comment by AaronCCWong** [comment]
Thank you for working on this! I will take a look at the PR asap.

**Comment by fizcoder** [comment]
Can this be done? Thanks.

**Comment by AaronCCWong** [comment]
@sbardian This looks great! Thanks for adding this.

**Pull request merged**
